### ISSUE TITLE
RepoDb - Fluent Query

### ISSUE THREAD

**Issue by mikependon** [TwentyFourMinutes/Venflow#1]
Hi, I am interested to see your benchmark result as this is targeting the PostgreSQL.

Can you take a look at [here](https://github.com/TwentyFourMinutes/Venflow/blob/7e76207a40b63bde6abc286a3ab22de6620ccc9b/src/Venflow/Venflow.Benchmarks/Benchmarks/QuerySingleAsyncBenchmark.cs#L37)? It seems it is querying all records the data from the DB and do the post filter in the client.

You can use the code below.

```csharp
connection.QueryAll<T>(top: 1);
```

For all `ToList()` method, can you use the `AsList()` method instead? Part of RepoDb.Extensions.

**Comment by TwentyFourMinutes** [comment]
Oh, for sure will do, thanks for letting me know. Will patch it as soon as possible. I will post benchmark results on my end once the first somewhat stable release is out, that's the reason for the missing README at the moment.
