### ISSUE TITLE
Default timestamp insert is not now() event if specified in db rule

### ISSUE THREAD

**Issue by Neoz-JourneyLab** [TwentyFourMinutes/Venflow#13]
### Describe the bug
Database timestampz column gets the value of '0001-12-31 23:42:30.000000 +00:00 BC' when inserting a new row, if the timestamp is not specified in entity. (Even if the database column has a default value of 'now()').

### Reproduction
```cs
  public class Interception {
    public Guid Id { get; set; }
    public DateTime gdh_inter { get; set; }
  }

  Interception i = new Interception();
  await db.Interceptions.InsertAsync(i);
```

### Further technical details
The only way to get rid of that bug for now is to specify defaut datetime in C# class : 
```cs
  public class Interception {
    public Guid Id { get; set; }
    public DateTime gdh_inter { get; set; } = DateTime.UtcNow; 
  }
```

**Comment by TwentyFourMinutes** [comment]
This issue was fixed with [this commit](https://github.com/TwentyFourMinutes/Venflow/commit/03107049be78c7379864599d2fdc656ed6b29a4d), in the next version you will be able to configure the column to have a default value in your `EntityConfiguration` with `.Column(x => x.gdh_inter).HasDefault()`.
