### ISSUE TITLE
RepoDb: QueryAll

### ISSUE THREAD

**Issue by mikependon** [TwentyFourMinutes/Venflow#2]
On this code [line](https://github.com/TwentyFourMinutes/Venflow/blob/749076fcd1c024cc3d8e91943d443edafabb0b09/src/Venflow/Venflow.Benchmarks/Benchmarks/QuerySingleAsyncBenchmark.cs#L37), I would highly recommend to use the `QueryAll<T>(top: X)` instead.

Like the on one in our [documentation](http://repodb.net/operation/queryall#filtering-the-results):

```csharp
using (var connection = new SqlConnection(connectionString).EnsureOpen())
{
	var people = connection.QueryAll<Person>(top: 100);
	// Do the stuffs for 'people' here
}
```

**Why?** By using the `where` on the `Query<T>()` would force writing the `WHERE (Field IS NOT NULL);` in which slow down the process (along the way) even though they're returning the same result.

**Comment by TwentyFourMinutes** [comment]
Thanks for the suggestion, however I am currently using `RepoDb 1.11.1-beta2` in which this overload doesn't exist, so the only suitable async version of this, which I could found was:
```cs
QueryAsync<Person>(whereOrPrimaryKey: null, top: 10000)
```
Feel free to suggest any other overloads of this method.

**Comment by mikependon** [comment]
And that is a shame on my side unknowingly about the change on the method arguments after I splitted the `QueryAll<T>()` from the `Query<T>()` itself. Then, you have done it correctly and by having that missing overload method could be in purpose historically.

I am just thinking to myself now why I wrote that on my documentation. Will update the documentation ASAP.
