### ISSUE TITLE
updations in the readme file

### ISSUE THREAD

**Issue by shubhamshah14102** [TwentyFourMinutes/Venflow#34]
Hey,
The contributing file has a scope of improvement and can be updated to a concise way after error removal.
I would like to contribute so please can you assign this issue to me.

**Comment by TwentyFourMinutes** [comment]
Hey there, I appreciate it a lot that you want to contribute to Venflow, however I am not quite sure what you are talking about. Could you please elaborate? From what I currently understand, you are seeing issues with the current state of the README which you want to improve, is that correct?

**Comment by shubhamshah14102** [comment]
"However, to keep things organized and well organized there are a few steps you should have gone through before creating an issue or a pull-request."
The following file in the contributing file is an incorrect use of English to mention similar things in one sentence.
A better concise ,replacement would be to keep one verb.
Besides when we mention the phrase "should have gone " , it indicates that one already has experienced that when we are trying to keep our norms in front.
A better updation from my end would be-
"However, to keep things  well organized there are a few steps you should go through before creating an issue or a pull-request."

**Comment by TwentyFourMinutes** [comment]
Oh yeah that is defiantly an issue, thanks for pointing it out. If you want to, you can create a PR if you would like to fix it.
